version: '3.7'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./default.template.conf:/etc/nginx/templates/default.conf.template
      - ./public:/var/www/html/public
    ports:
      - 1111:80
